### ISSUE TITLE
Muito bom!!!

### ISSUE THREAD

**Issue by guguxh** [gabrielbrop/haxball-extended-room#1]
Muito bom!!!! Congratulations my friend!!

**Comment by MasterOfCuriosity** [comment]
Ai, @guguxh você pode ajudar com isso? Estou me embolando pra juntar o DISCORD.JS

**Comment by guguxh** [comment]
Claro que posso! Qual o seu problema?

**Comment by gabrielbrunop** [comment]
> Ai, @guguxh você pode ajudar com isso? Estou me embolando pra juntar o DISCORD.JS

Atualmente não é possível fazer integração direta do Discord com uma sala de Haxball, já que a API do Discord não funciona no navegador. O que você pode fazer é uma conexão WebSocket com um servidor no localhost. Existem diversas libraries de WS, mas você pode dar uma olhada [nesta](https://github.com/websockets/ws).

Assim, quando um evento acontecer (como um usuário mandar uma mensagem), você envia uma mensagem para o servidor WebSocket em que estiver conectado, assim como também pode enviar mensagens do servidor ao cliente quando, por exemplo, um usuário do Discord executar um comando.

Outras soluções poderiam ser utilizar a função `evaluate` do Puppeteer ou uma API REST.

**Comment by MasterOfCuriosity** [comment]
@gabrielbrop você tem discord? Estou a procura de um programador onde saiba fazer isso, assim que seja, irei abrir diversas salas, e assim ter uma "ligação" entre o Discord e as salas de Haxball.
